# This is a basic workflow to help you get started with Actions

name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  runs-on: ${{ matrix.os }}
  strategy:
    matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
  steps:
    - name: Setup Ubuntu
      run : echo "I am in " matrix.os
