# This is a basic workflow to help you get started with Actions

name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        
    - name: build      
      shell: bash
      run: |
        make
        
    - uses: actions/upload-artifact@v3
      with:
        name: "${{ runner.os }} output"
        path: output
