# This is a basic workflow to help you get started with Actions

name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        build_type: [RelWithDebInfo, Debug]
        enable_ui: [off]
        include:
          - os: ubuntu-latest
            build_type: Debug
            enable_ui: on
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: build      
      shell: bash
      run: |
        make
    - uses: actions/upload-artifact@v3
      with:
        name: "${{ runner.os }} output"
        path: output
